import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { AppError } from '../../common/errors/app-error.js'
import {
  buildObjectKey,
  isSafeObjectKey,
  resolveLocalStorageRoot,
  resolveLocalObjectPath,
} from './object-key.js'

const UUID = '550e8400-e29b-41d4-a716-446655440000'
const NOW = new Date('2026-09-13T08:00:00.000Z')

describe('buildObjectKey', () => {
  it('builds media/<yyyy>/<mm>/<uuid>.<ext> from the validated mime type', () => {
    expect(buildObjectKey('image/webp', NOW, UUID)).toBe(`media/2026/09/${UUID}.webp`)
    expect(buildObjectKey('image/jpeg', NOW, UUID)).toBe(`media/2026/09/${UUID}.jpg`)
    expect(buildObjectKey('image/png', NOW, UUID)).toBe(`media/2026/09/${UUID}.png`)
    expect(buildObjectKey('image/avif', NOW, UUID)).toBe(`media/2026/09/${UUID}.avif`)
  })

  it('is case/space tolerant for the mime type and pads single-digit months', () => {
    expect(buildObjectKey('  IMAGE/WEBP ', new Date('2026-01-02T00:00:00.000Z'), UUID)).toBe(
      `media/2026/01/${UUID}.webp`,
    )
  })

  it('never uses the client filename and always produces a safe key', () => {
    const key = buildObjectKey('image/png', NOW, UUID)

    expect(key).not.toContain('..')
    expect(key).not.toContain('\\')
    expect(isSafeObjectKey(key)).toBe(true)
  })

  it('rejects mime types outside the V1 image whitelist', () => {
    for (const mimeType of [
      'image/svg+xml',
      'image/gif',
      'application/pdf',
      'video/mp4',
      'application/octet-stream',
    ]) {
      expect(() => buildObjectKey(mimeType, NOW, UUID)).toThrowError(AppError)

      try {
        buildObjectKey(mimeType, NOW, UUID)
      } catch (error) {
        expect((error as AppError).code).toBe('FILE_UPLOAD_ERROR')
        expect((error as AppError).status).toBe(422)
      }
    }
  })
})

describe('isSafeObjectKey', () => {
  it('accepts keys generated by the policy', () => {
    expect(isSafeObjectKey(`media/2026/09/${UUID}.jpg`)).toBe(true)
  })

  it('rejects traversal, absolute paths, wrong extensions and legacy/foreign formats', () => {
    for (const key of [
      '../../etc/passwd',
      '/media/2026/09/x.png',
      'media/2026/09/../../../secret.png',
      'media/2026/09/not-a-uuid.png',
      `media/2026/13/${UUID}.png`,
      `media/2026/09/${UUID}.exe`,
      `media/2026/09/${UUID}.svg`,
      'seed/placeholder-1.webp',
      'media\\2026\\09\\x.png',
      '',
    ]) {
      expect(isSafeObjectKey(key)).toBe(false)
    }
  })

  it('rejects non-string input including null bytes', () => {
    expect(isSafeObjectKey(null)).toBe(false)
    expect(isSafeObjectKey(undefined)).toBe(false)
    expect(isSafeObjectKey(42)).toBe(false)
    expect(isSafeObjectKey(`media/2026/09/${UUID}.png\0`)).toBe(false)
  })
})

describe('resolveLocalObjectPath', () => {
  it('resolves a safe key inside the configured root', () => {
    const root = path.resolve('E:/tmp/media-root')
    const resolved = resolveLocalObjectPath(root, `media/2026/09/${UUID}.webp`)

    expect(resolved).toBe(path.resolve(root, 'media', '2026', '09', `${UUID}.webp`))
  })

  it('rejects unsafe keys before touching the filesystem', () => {
    const root = path.resolve('E:/tmp/media-root')

    expect(() => resolveLocalObjectPath(root, '../../../etc/passwd')).toThrowError(AppError)
    expect(() => resolveLocalObjectPath(root, 'media/2026/09/../../x.png')).toThrowError(AppError)
  })
})

describe('resolveLocalStorageRoot', () => {
  it('defaults to the local bucket root <cwd>/.data', () => {
    expect(resolveLocalStorageRoot(undefined, 'E:/Projects/Eson_web/backend')).toBe(
      path.resolve('E:/Projects/Eson_web/backend/.data'),
    )
    expect(resolveLocalStorageRoot('   ', 'E:/Projects/Eson_web/backend')).toBe(
      path.resolve('E:/Projects/Eson_web/backend/.data'),
    )
  })

  it('honours an explicit root', () => {
    expect(resolveLocalStorageRoot('E:/media-store', 'E:/whatever')).toBe(path.resolve('E:/media-store'))
    expect(resolveLocalStorageRoot('./custom-media', 'E:/base')).toBe(path.resolve('E:/base/custom-media'))
  })
})
